package goldilocks

import (
	fp "github.com/cloudflare/circl/math/fp448"
)

// Point is a point on the Goldilocks Curve.
type Point struct{ x, y, z, ta, tb fp.Elt }

func (P Point) String() string { _ = "STUB: not implemented"; return "" }

// FromAffine creates a point from affine coordinates.
func FromAffine(x, y *fp.Elt) (*Point, error) { _ = "STUB: not implemented"; return nil, nil }

// isLessThan returns true if 0 <= x < y, and assumes that slices are of the
// same length and are interpreted in little-endian order.
func isLessThan(x, y []byte) bool { _ = "STUB: not implemented"; return false }

// FromBytes returns a point from the input buffer.
func FromBytes(in []byte) (*Point, error) { _ = "STUB: not implemented"; return nil, nil }

// u = y^2
// v = dy^2
// u = y^2-1
// v = dy^2-1
// x = sqrt(u/v)

// x = x mod p

// IsIdentity returns true is P is the identity Point.
func (P *Point) IsIdentity() bool { _ = "STUB: not implemented"; return false }

// IsEqual returns true if P is equivalent to Q.
func (P *Point) IsEqual(Q *Point) bool { _ = "STUB: not implemented"; return false }

// Neg obtains the inverse of the Point.
func (P *Point) Neg() { _ = "STUB: not implemented"; return }

// ToAffine returns the x,y affine coordinates of P.
func (P *Point) ToAffine() (x, y fp.Elt) {
	_ = "STUB: not implemented"
	return *
	// 1/z
	new(fp.Elt), *new(fp.Elt)
}

// x/z
// y/z

// ToBytes stores P into a slice of bytes.
func (P *Point) ToBytes(out []byte) error { _ = "STUB: not implemented"; return nil }

// MarshalBinary encodes the receiver into a binary form and returns the result.
func (P *Point) MarshalBinary() (data []byte, err error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// UnmarshalBinary must be able to decode the form generated by MarshalBinary.
func (P *Point) UnmarshalBinary(data []byte) error { _ = "STUB: not implemented"; return nil }

// Double sets P = 2Q.
func (P *Point) Double() {
	_ = "STUB: not implemented"

	// Add sets P =P+Q..
	return
}

func (P *Point) Add(Q *Point) {
	_ = "STUB: not implemented"
	// This is formula (5) from "Twisted Edwards Curves Revisited" by
	// Hisil H., Wong K.KH., Carter G., Dawson E. (2008)
	// https://doi.org/10.1007/978-3-540-89255-7_20
	return
}

// t1 = ta1*tb1
// t2 = ta2*tb2
// A = x1*x2
// B = y1*y2
// t1*t2
// C = d*t1*t2
// D = z1*z2
// x1+y1
// x2+y2
// (x1+y1)*(x2+y2)
// (x1+y1)*(x2+y2)-A
// E = (x1+y1)*(x2+y2)-A-B
// F = D-C
// G = D+C
// H = B-A
// Z = F * G
// X = E * F
// Y = G * H, T = E * H
