// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots.

//go:build purego || !amd64
// +build purego !amd64

package p434

import (
	"github.com/cloudflare/circl/dh/sidh/internal/common"
)

// Compute z = x + y (mod p).
func addP434(z, x, y *common.Fp) {
	_ = "STUB: not implemented"

	// z=x+y % P434
	return
}

// z = z - P434x2

// if z<0 add P434x2 back

// Compute z = x - y (mod p).
func subP434(z, x, y *common.Fp) { _ = "STUB: not implemented"; return }

// If choice = 0, leave x unchanged. If choice = 1, sets x to y.
// If choice is neither 0 nor 1 then behaviour is undefined.
// This function executes in constant time.
func cmovP434(x, y *common.Fp, choice uint8) { _ = "STUB: not implemented"; return }

// Conditionally swaps bits in x and y in constant time.
// mask indicates bits to be swapped (set bits are swapped)
// For details see "Hackers Delight, 2.20"
//
// Implementation doesn't actually depend on a prime field.
func cswapP434(x, y *common.Fp, mask uint8) { _ = "STUB: not implemented"; return }

// Perform Montgomery reduction: set z = x R^{-1} (mod 2*p)
// with R=2^(FpWords*64). Destroys the input value.
func rdcP434(z *common.Fp, x *common.FpX2) { _ = "STUB: not implemented"; return }

// Compute z = x * y.
func mulP434(z *common.FpX2, x, y *common.Fp) { _ = "STUB: not implemented"; return }

// Compute z = x + y, without reducing mod p.
func adlP434(z, x, y *common.FpX2) { _ = "STUB: not implemented"; return }

// Reduce a field element in [0, 2*p) to one in [0,p).
func modP434(x *common.Fp) { _ = "STUB: not implemented"; return }

// Sets all bits if borrow = 1

// Compute z = x - y, without reducing mod p.
func sulP434(z, x, y *common.FpX2) { _ = "STUB: not implemented"; return }

// Sets all bits if borrow = 1
