// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots.

package p434

import (
	"github.com/cloudflare/circl/dh/sidh/internal/common"
)

// Montgomery multiplication. Input values must be already
// in Montgomery domain.
func mulP(dest, lhs, rhs *common.Fp) { _ = "STUB: not implemented"; return }

// = a*b*R*R
// = a*b*R mod p

// Set dest = x^((p-3)/4).  If x is square, this is 1/sqrt(x).
// Uses variation of sliding-window algorithm from with window size
// of 5 and least to most significant bit sliding (left-to-right)
// See HAC 14.85 for general description.
//
// Allowed to overlap x with dest.
// All values in Montgomery domains
// Set dest = x^(2^k), for k >= 1, by repeated squarings.
func p34(dest, x *common.Fp) { _ = "STUB: not implemented"; return }

// This performs sum(powStrategy) + 1 squarings and len(lookup) + len(mulStrategy)
// multiplications.

// Precompute lookup table of odd multiples of x for window
// size k=5.

// Now lookup = {x, x^3, x^5, ... }
// so that lookup[i] = x^{2*i + 1}
// so that lookup[k/2] = x^k, for odd k

func add(dest, lhs, rhs *common.Fp2) { _ = "STUB: not implemented"; return }

func sub(dest, lhs, rhs *common.Fp2) { _ = "STUB: not implemented"; return }

func mul(dest, lhs, rhs *common.Fp2) { _ = "STUB: not implemented"; return }

// Let (a,b,c,d) = (lhs.a,lhs.b,rhs.a,rhs.b).
//
// (a + bi)*(c + di) = (a*c - b*d) + (a*d + b*c)i
//
// Use Karatsuba's trick: note that
//
// (b - a)*(c - d) = (b*c + a*d) - a*c - b*d
//
// so (a*d + b*c) = (b-a)*(c-d) + a*c + b*d.
// = (b-a)*R
// = (c-d)*R
// = a*c*R*R
// = b*d*R*R
// = (b-a)*(c-d)*R*R
// = ((b-a)*(c-d) + a*c)*R*R
// = ((b-a)*(c-d) + a*c + b*d)*R*R
// = (a*d + b*c)*R mod p
// = (a*c - b*d)*R*R
// = (a*c - b*d)*R mod p

// Set dest = 1/x
//
// Allowed to overlap dest with x.
//
// Returns dest to allow chaining operations.
func inv(dest, x *common.Fp2) { _ = "STUB: not implemented"; return }

// We want to compute
//
//    1          1     (a - bi)	    (a - bi)
// -------- = -------- -------- = -----------
// (a + bi)   (a + bi) (a - bi)   (a^2 + b^2)
//
// Letting c = 1/(a^2 + b^2), this is
//
// 1/(a+bi) = a*c - b*ci.

// = a*a*R*R
// = b*b*R*R
// = (a^2 + b^2)*R*R
// = (a^2 + b^2)*R mod p
// Now f1 = a^2 + b^2

func sqr(dest, x *common.Fp2) { _ = "STUB: not implemented"; return }

// (a + bi)*(a + bi) = (a^2 - b^2) + 2abi.
// = a*R + a*R = 2*a*R
// = a*R + b*R = (a+b)*R
// = a*R - b*R = (a-b)*R
// = (a+b)*(a-b)*R*R = (a^2 - b^2)*R*R
// = 2*a*b*R*R
// = (a^2 - b^2)*R mod p
// = 2*a*b*R mod p

// In case choice == 1, performs following swap in constant time:
//
// xPx <-> xQx
// xPz <-> xQz
//
// Otherwise returns xPx, xPz, xQx, xQz unchanged
func cswap(xPx, xPz, xQx, xQz *common.Fp2, choice uint8) { _ = "STUB: not implemented"; return }

// In case choice == 1, performs following moves in constant time:
//
// xPx <- xQx
// xPz <- xQz
//
// Otherwise returns xPx, xPz, xQx, xQz unchanged
func cmov(xPx, xPz, xQx, xQz *common.Fp2, choice uint8) { _ = "STUB: not implemented"; return }

func isZero(x *common.Fp2) uint8 { _ = "STUB: not implemented"; return 0 }

// Converts in.A and in.B to Montgomery domain and stores
// in 'out'
// out.A = in.A * R mod p
// out.B = in.B * R mod p
// Performs v = v*R^2*R^(-1) mod p, for both in.A and in.B
func ToMontgomery(out, in *common.Fp2) {
	_ = "STUB: not implemented"

	// a*R*R
	return
}

// a*R mod p

// Converts in.A and in.B from Montgomery domain and stores
// in 'out'
// out.A = in.A mod p
// out.B = in.B mod p
//
// After returning from the call 'in' is not modified.
func FromMontgomery(out, in *common.Fp2) {
	_ = "STUB: not implemented"

	// convert from montgomery domain
	return
}

// = a mod p in [0, 2p)
// = a mod p in [0, p)
