// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots.

//go:build purego || (!amd64 && !arm64)
// +build purego !amd64,!arm64

package p503

import (
	"github.com/cloudflare/circl/dh/sidh/internal/common"
)

// Compute z = x + y (mod p).
func addP503(z, x, y *common.Fp) {
	_ = "STUB: not implemented"

	// z=x+y % P503
	return
}

// z = z - P503x2

// if z<0 add P503x2 back

// Compute z = x - y (mod p).
func subP503(z, x, y *common.Fp) { _ = "STUB: not implemented"; return }

// If choice = 0, leave x unchanged. If choice = 1, sets x to y.
// If choice is neither 0 nor 1 then behaviour is undefined.
// This function executes in constant time.
func cmovP503(x, y *common.Fp, choice uint8) { _ = "STUB: not implemented"; return }

// Conditionally swaps bits in x and y in constant time.
// mask indicates bits to be swapped (set bits are swapped)
// For details see "Hackers Delight, 2.20"
//
// Implementation doesn't actually depend on a prime field.
func cswapP503(x, y *common.Fp, mask uint8) { _ = "STUB: not implemented"; return }

// Perform Montgomery reduction: set z = x R^{-1} (mod 2*p)
// with R=2^(FpWords*64). Destroys the input value.
func rdcP503(z *common.Fp, x *common.FpX2) { _ = "STUB: not implemented"; return }

// Compute z = x * y.
func mulP503(z *common.FpX2, x, y *common.Fp) { _ = "STUB: not implemented"; return }

// Compute z = x + y, without reducing mod p.
func adlP503(z, x, y *common.FpX2) { _ = "STUB: not implemented"; return }

// Reduce a field element in [0, 2*p) to one in [0,p).
func modP503(x *common.Fp) { _ = "STUB: not implemented"; return }

// Sets all bits if borrow = 1

// Compute z = x - y, without reducing mod p.
func sulP503(z, x, y *common.FpX2) { _ = "STUB: not implemented"; return }

// Sets all bits if borrow = 1
