// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots.

package p751

import (
	. "github.com/cloudflare/circl/dh/sidh/internal/common"
)

// -----------------------------------------------------------------------------
// Functions for traversing isogeny trees according to strategy. Key type 'A' is
//

// Traverses isogeny tree in order to compute xR, xP, xQ and xQmP needed
// for public key generation.
func traverseTreePublicKeyA(curve *ProjectiveCurveParameters, xR, phiP, phiQ, phiR *ProjectivePoint) {
	_ = "STUB: not implemented"
	return
}

// pop xR from points

// Traverses isogeny tree in order to compute xR needed
// for public key generation.
func traverseTreeSharedKeyA(curve *ProjectiveCurveParameters, xR *ProjectivePoint) {
	_ = "STUB: not implemented"
	return
}

// pop xR from points

// Traverses isogeny tree in order to compute xR, xP, xQ and xQmP needed
// for public key generation.
func traverseTreePublicKeyB(curve *ProjectiveCurveParameters, xR, phiP, phiQ, phiR *ProjectivePoint) {
	_ = "STUB: not implemented"
	return
}

// pop xR from points

// Traverses isogeny tree in order to compute xR, xP, xQ and xQmP needed
// for public key generation.
func traverseTreeSharedKeyB(curve *ProjectiveCurveParameters, xR *ProjectivePoint) {
	_ = "STUB: not implemented"
	return
}

// pop xR from points

// Generate a public key in the 2-torsion group. Public key is a set
// of three x-coordinates: xP,xQ,x(P-Q), where P,Q are points on E_a(Fp2)
func PublicKeyGenA(pub3Pt *[3]Fp2, prvBytes []byte) { _ = "STUB: not implemented"; return }

// Load points for A

// Load points for B

// Find isogeny kernel

// Secret isogeny

// Generate a public key in the 2-torsion group. Public key is a set
// of three x-coordinates: xP,xQ,x(P-Q), where P,Q are points on E_a(Fp2)
func PublicKeyGenB(pub3Pt *[3]Fp2, prvBytes []byte) { _ = "STUB: not implemented"; return }

// Load points for B

// Load points for A

// Find isogeny kernel

// -----------------------------------------------------------------------------
// Key agreement functions
//

// Establishing shared keys in in 2-torsion group
func DeriveSecretA(ss, prv []byte, pub3Pt *[3]Fp2) { _ = "STUB: not implemented"; return }

// Recover curve coefficients

// Find kernel of the morphism

// Traverse isogeny tree

// Calculate j-invariant on isogenous curve

// Establishing shared keys in in 3-torsion group
func DeriveSecretB(ss, prv []byte, pub3Pt *[3]Fp2) { _ = "STUB: not implemented"; return }

// Recover curve coefficients

// Find kernel of the morphism

//PUBLIC KEY VALIDATION

// Traverse isogeny tree

// Calculate j-invariant on isogenous curve
