// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots.

package p751

import (
	. "github.com/cloudflare/circl/dh/sidh/internal/common"
)

// Stores isogeny 3 curve constants
type isogeny3 struct {
	K1 Fp2
	K2 Fp2
}

// Stores isogeny 4 curve constants
type isogeny4 struct {
	isogeny3
	K3 Fp2
}

// Computes j-invariant for a curve y2=x3+A/Cx+x with A,C in F_(p^2). Result
// is returned in jBytes buffer, encoded in little-endian format. Caller
// provided jBytes buffer has to be big enough to j-invariant value. In case
// of SIDH, buffer size must be at least size of shared secret.
// Implementation corresponds to Algorithm 9 from SIKE.
func Jinvariant(cparams *ProjectiveCurveParameters, j *Fp2) { _ = "STUB: not implemented"; return }

// j  = A^2
// t1 = C^2
// t0 = t1 + t1
// t0 = j - t0
// t0 = t0 - t1
// t0 = t0 - t1
// t1 = t1^2
// j = j * t1
// t0 = t0 + t0
// t0 = t0 + t0
// t1 = t0^2
// t0 = t0 * t1
// t0 = t0 + t0
// t0 = t0 + t0
// j  = 1/j
// j  = t0 * j

// Given affine points x(P), x(Q) and x(Q-P) in a extension field F_{p^2}, function
// recovers projective coordinate A of a curve. This is Algorithm 10 from SIKE.
func RecoverCoordinateA(curve *ProjectiveCurveParameters, xp, xq, xr *Fp2) {
	_ = "STUB: not implemented"
	return
}

// t1 = Xp + Xq
// t0 = Xp * Xq
// A  = X(q-p) * t1
// A  = A + t0
// t0 = t0 * X(q-p)
// A  = A - 1
// t0 = t0 + t0
// t1 = t1 + X(q-p)
// t0 = t0 + t0
// A  = A^2
// t0 = 1/t0
// A  = A * t0
// A  = A - t1

// Computes equivalence (A:C) ~ (A+2C : A-2C)
func CalcCurveParamsEquiv3(cparams *ProjectiveCurveParameters) CurveCoefficientsEquiv {
	_ = "STUB: not implemented"
	return *new(CurveCoefficientsEquiv)
}

// A24p = A+2*C

// A24m = A-2*C

// Computes equivalence (A:C) ~ (A+2C : 4C)
func CalcCurveParamsEquiv4(cparams *ProjectiveCurveParameters) CurveCoefficientsEquiv {
	_ = "STUB: not implemented"
	return *new(CurveCoefficientsEquiv)
}

// A24p = A+2C

// C24 = 4*C

// Helper function for RightToLeftLadder(). Returns A+2C / 4.
func CalcAplus2Over4(cparams *ProjectiveCurveParameters) (ret Fp2) {
	_ = "STUB: not implemented"

	// 2C
	return *new(Fp2)
}

// A+2C

// 1/4C

// A+2C/4C

// Recovers (A:C) curve parameters from projectively equivalent (A+2C:A-2C).
func RecoverCurveCoefficients3(cparams *ProjectiveCurveParameters, coefEq *CurveCoefficientsEquiv) {
	_ = "STUB: not implemented"
	return
}

// cparams.A = 2*(A+2C+A-2C) = 4A

// cparams.C = (A+2C-A+2C) = 4C

// Recovers (A:C) curve parameters from projectively equivalent (A+2C:4C).
func RecoverCurveCoefficients4(cparams *ProjectiveCurveParameters, coefEq *CurveCoefficientsEquiv) {
	_ = "STUB: not implemented"
	// cparams.C = (4C)*1/2=2C
	return
}

// cparams.A = A+2C - 2C = A

// cparams.C = 2C * 1/2 = C

// Combined coordinate doubling and differential addition. Takes projective points
// P,Q,Q-P and (A+2C)/4C curve E coefficient. Returns 2*P and P+Q calculated on E.
// Function is used only by RightToLeftLadder. Corresponds to Algorithm 5 of SIKE
func xDbladd(P, Q, QmP *ProjectivePoint, a24 *Fp2) (dblP, PaQ ProjectivePoint) {
	_ = "STUB: not implemented"
	return *new(ProjectivePoint), *new(ProjectivePoint)
}

// t0   = Xp+Zp
// t1   = Xp-Zp
// 2P.X = t0^2
// t2   = Xq-Zq
// Xp+q = Xq+Zq
// t0   = t0 * t2
// 2P.Z = t1 * t1
// t1   = t1 * Xp+q
// t2   = 2P.X - 2P.Z
// 2P.X = 2P.X * 2P.Z
// Xp+q = A24 * t2
// Zp+q = t0 - t1
// 2P.Z = Xp+q + 2P.Z
// Xp+q = t0 + t1
// 2P.Z = 2P.Z * t2
// Zp+q = Zp+q ^ 2
// Xp+q = Xp+q ^ 2
// Zp+q = Xq-p * Zp+q
// Xp+q = Zq-p * Xp+q

// Given the curve parameters, xP = x(P), computes xP = x([2^k]P)
// Safe to overlap xP, x2P.
func Pow2k(xP *ProjectivePoint, params *CurveCoefficientsEquiv, k uint32) {
	_ = "STUB: not implemented"
	return
}

// t0  = Xp - Zp
// t1  = Xp + Zp
// t0  = t0 ^ 2
// t1  = t1 ^ 2
// Z2p = C24 * t0
// X2p = Z2p * t1
// t1  = t1 - t0
// t0  = A24+ * t1
// Z2p = Z2p + t0
// Zp  = Z2p * t1

// Given the curve parameters, xP = x(P), and k >= 0, compute xP = x([3^k]P).
//
// Safe to overlap xP, xR.
func Pow3k(xP *ProjectivePoint, params *CurveCoefficientsEquiv, k uint32) {
	_ = "STUB: not implemented"
	return
}

// t0  = Xp - Zp
// t2  = t0^2
// t1  = Xp + Zp
// t3  = t1^2
// t4  = t1 + t0
// t0  = t1 - t0
// t1  = t4^2
// t1  = t1 - t3
// t1  = t1 - t2
// t5  = t3 * A24+
// t3  = t5 * t3
// t6  = t2 * A24-
// t2  = t2 * t6
// t3  = t2 - t3
// t2  = t5 - t6
// t1  = t2 * t1
// t2  = t3 + t1
// t2  = t2^2
// X3p = t2 * t4
// t1  = t3 - t1
// t1  = t1^2
// Z3p = t1 * t0

// Set (y1, y2, y3)  = (1/x1, 1/x2, 1/x3).
//
// All xi, yi must be distinct.
func Fp2Batch3Inv(x1, x2, x3, y1, y2, y3 *Fp2) { _ = "STUB: not implemented"; return }

// x1*x2
// 1/(x1*x2*x3)

// 1/x1

// 1/x2

// 1/x3

// Scalarmul3Pt is a right-to-left point multiplication that given the
// x-coordinate of P, Q and P-Q calculates the x-coordinate of R=Q+[scalar]P.
// nbits must be smaller or equal to len(scalar).
func ScalarMul3Pt(cparams *ProjectiveCurveParameters, P, Q, PmQ *ProjectivePoint, nbits uint, scalar []uint8) ProjectivePoint {
	_ = "STUB: not implemented"
	return *new(ProjectivePoint)
}

// Iterate over the bits of the scalar, bottom to top

// Given a three-torsion point p = x(PB) on the curve E_(A:C), construct the
// three-isogeny phi : E_(A:C) -> E_(A:C)/<P_3> = E_(A':C').
//
// Input: (XP_3: ZP_3), where P_3 has exact order 3 on E_A/C
// Output:
//   - Curve coordinates (A' + 2C', A' - 2C') corresponding to E_A'/C' = A_E/C/<P3>
//   - Isogeny phi with constants in F_p^2
func (phi *isogeny3) GenerateCurve(p *ProjectivePoint) CurveCoefficientsEquiv {
	_ = "STUB: not implemented"
	return *new(CurveCoefficientsEquiv)
}

// K1 = XP3 - ZP3
// t0 = K1^2
// K2 = XP3 + ZP3
// t1 = K2^2
// t2 = t0 + t1
// t3 = K1 + K2
// t3 = t3^2
// t3 = t3 - t2
// t2 = t1 + t3
// t3 = t3 + t0
// t4 = t3 + t0
// t4 = t4 + t4
// t4 = t1 + t4
// A24m = t2 * t4
// t4 = t1 + t2
// t4 = t4 + t4
// t4 = t0 + t4
// t4 = t3 * t4
// t0 = t4 - A24m
// A24p = A24m + t0

// Given a 3-isogeny phi and a point pB = x(PB), compute x(QB), the x-coordinate
// of the image QB = phi(PB) of PB under phi : E_(A:C) -> E_(A':C').
//
// The output xQ = x(Q) is then a point on the curve E_(A':C'); the curve
// parameters are returned by the GenerateCurve function used to construct phi.
func (phi *isogeny3) EvaluatePoint(p *ProjectivePoint) { _ = "STUB: not implemented"; return }

// t0 = XQ + ZQ
// t1 = XQ - ZQ
// t2 = K1 * t0
// t1 = K2 * t1
// t2 = t0 + t1
// t0 = t1 - t0
// t2 = t2 ^ 2
// t0 = t0 ^ 2
// XQ'= XQ * t2
// ZQ'= ZQ * t0

// Given a four-torsion point p = x(PB) on the curve E_(A:C), construct the
// four-isogeny phi : E_(A:C) -> E_(A:C)/<P_4> = E_(A':C').
//
// Input: (XP_4: ZP_4), where P_4 has exact order 4 on E_A/C
// Output:
//   - Curve coordinates (A' + 2C', 4C') corresponding to E_A'/C' = A_E/C/<P4>
//   - Isogeny phi with constants in F_p^2
func (phi *isogeny4) GenerateCurve(p *ProjectivePoint) CurveCoefficientsEquiv {
	_ = "STUB: not implemented"
	return *new(CurveCoefficientsEquiv)
}

// Given a 4-isogeny phi and a point xP = x(P), compute x(Q), the x-coordinate
// of the image Q = phi(P) of P under phi : E_(A:C) -> E_(A':C').
//
// Input: Isogeny returned by GenerateCurve and point q=(Qx,Qz) from E0_A/C
// Output: Corresponding point q from E1_A'/C', where E1 is 4-isogenous to E0
func (phi *isogeny4) EvaluatePoint(p *ProjectivePoint) { _ = "STUB: not implemented"; return }

// PublicKeyValidation preforms public key/ciphertext validation using the CLN test.
// CLN test: Check that P and Q are both of order 3^e3 and they generate the torsion E_A[3^e3]
// A countermeasure for remote timing attacks on SIKE; suggested by https://eprint.iacr.org/2022/054.pdf
// Any curve E_A (SIKE 434, 503, 751) that passes CLN test is supersingular.
// Input: The public key / ciphertext P, Q, PmQ. The projective coordinate A of the curve defined by (P, Q, PmQ)
// Outputs: Whether (P,Q,PmQ) follows the CLN test
func PublicKeyValidation(cparams *ProjectiveCurveParameters, P, Q, PmQ *ProjectivePoint, nbits uint) error {
	_ = "STUB: not implemented"
	return nil
}

// PmQ is not point T or O

// Compute e_3 = log3(2^(nbits+1))

// Verify that P and Q generate E_A[3^e_3] by checking: [3^(e_3-1)]P != [+-3^(e_3-1)]Q

// P, Q are not of full order 3^e_3

// PX/PZ = affine(PX)
// QX/QZ = affine(QX)
// If PX/PZ = QX/QZ, we have P=+-Q

// [3^(e_3-1)]P == [+-3^(e_3-1)]Q

// Check that Ord(P) = Ord(Q) = 3^(e_3)

// P, Q are not of correct order 3^e_3
