package group

import (
	"crypto"
	"crypto/ecdh"
	"crypto/elliptic"
	_ "crypto/sha256"
	_ "crypto/sha512"
	"io"
	"math/big"

	optP384 "github.com/cloudflare/circl/ecc/p384"
	"golang.org/x/crypto/cryptobyte"
)

var (
	// P256 is the group generated by P-256 elliptic curve.
	P256 Group = wG{ellC: elliptic.P256, ecdhC: ecdh.P256, c: elliptic.P256(), order: orderP256[:]}
	// P384 is the group generated by P-384 elliptic curve.
	P384 Group = wG{ellC: elliptic.P384, ecdhC: ecdh.P384, c: optP384.P384(), order: orderP384[:]}
	// P521 is the group generated by P-521 elliptic curve.
	P521 Group = wG{ellC: elliptic.P521, ecdhC: ecdh.P521, c: elliptic.P521(), order: orderP521[:]}
)

type wG struct {
	c     elliptic.Curve
	ellC  func() elliptic.Curve
	ecdhC func() ecdh.Curve
	order []byte
}

func (g wG) String() string                     { _ = "STUB: not implemented"; return "" }
func (g wG) NewElement() Element                { _ = "STUB: not implemented"; return *new(Element) }
func (g wG) NewScalar() Scalar                  { _ = "STUB: not implemented"; return *new(Scalar) }
func (g wG) Identity() Element                  { _ = "STUB: not implemented"; return *new(Element) }
func (g wG) byteSize() int                      { _ = "STUB: not implemented"; return 0 }
func (g wG) zeroScalar() *wScl                  { _ = "STUB: not implemented"; return nil }
func (g wG) zeroElement() *wElt                 { _ = "STUB: not implemented"; return nil }
func (g wG) Generator() Element                 { _ = "STUB: not implemented"; return *new(Element) }
func (g wG) RandomElement(rd io.Reader) Element { _ = "STUB: not implemented"; return *new(Element) }

func (g wG) RandomScalar(rd io.Reader) Scalar { _ = "STUB: not implemented"; return *new(Scalar) }

func (g wG) RandomNonZeroScalar(rd io.Reader) Scalar {
	_ = "STUB: not implemented"
	return *new(Scalar)
}

func (g wG) cvtElt(e Element) *wElt { _ = "STUB: not implemented"; return nil }

func (g wG) cvtScl(s Scalar) *wScl { _ = "STUB: not implemented"; return nil }

func (g wG) Params() *Params { _ = "STUB: not implemented"; return nil }

func (g wG) HashToElementNonUniform(b, dst []byte) Element {
	_ = "STUB: not implemented"
	return *new(Element)
}

func (g wG) HashToElement(b, dst []byte) Element { _ = "STUB: not implemented"; return *new(Element) }

func (g wG) HashToScalar(b, dst []byte) Scalar { _ = "STUB: not implemented"; return *new(Scalar) }

type wElt struct {
	x, y *big.Int
	wG
}

func (e *wElt) Group() Group           { _ = "STUB: not implemented"; return *new(Group) }
func (e *wElt) String() string         { _ = "STUB: not implemented"; return "" }
func (e *wElt) IsIdentity() bool       { _ = "STUB: not implemented"; return false }
func (e *wElt) IsEqual(o Element) bool { _ = "STUB: not implemented"; return false }

func (e *wElt) Set(a Element) Element { _ = "STUB: not implemented"; return *new(Element) }

func (e *wElt) Copy() Element { _ = "STUB: not implemented"; return *new(Element) }

func (e *wElt) CMov(v int, a Element) Element { _ = "STUB: not implemented"; return *new(Element) }

func (e *wElt) CSelect(v int, a Element, b Element) Element {
	_ = "STUB: not implemented"
	return *new(Element)
}

func (e *wElt) Add(a, b Element) Element { _ = "STUB: not implemented"; return *new(Element) }

func (e *wElt) Dbl(a Element) Element { _ = "STUB: not implemented"; return *new(Element) }

func (e *wElt) Neg(a Element) Element { _ = "STUB: not implemented"; return *new(Element) }

func (e *wElt) Mul(a Element, s Scalar) Element { _ = "STUB: not implemented"; return *new(Element) }

func (e *wElt) MulGen(s Scalar) Element { _ = "STUB: not implemented"; return *new(Element) }

func (e *wElt) MarshalBinary() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

func (e *wElt) MarshalBinaryCompress() ([]byte, error) { _ = "STUB: not implemented"; return nil, nil }

func (e *wElt) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }

// point at infinity

// compressed

// uncompressed

type wScl struct {
	wG
	k []byte
}

func (s *wScl) Group() Group              { _ = "STUB: not implemented"; return *new(Group) }
func (s *wScl) String() string            { _ = "STUB: not implemented"; return "" }
func (s *wScl) SetUint64(n uint64) Scalar { _ = "STUB: not implemented"; return *new(Scalar) }

func (s *wScl) SetBigInt(x *big.Int) Scalar { _ = "STUB: not implemented"; return *new(Scalar) }

func (s *wScl) IsZero() bool { _ = "STUB: not implemented"; return false }

func (s *wScl) IsEqual(a Scalar) bool { _ = "STUB: not implemented"; return false }

func (s *wScl) Set(a Scalar) Scalar { _ = "STUB: not implemented"; return *new(Scalar) }

func (s *wScl) Copy() Scalar { _ = "STUB: not implemented"; return *new(Scalar) }

func (s *wScl) CMov(v int, a Scalar) Scalar { _ = "STUB: not implemented"; return *new(Scalar) }

func (s *wScl) CSelect(v int, a Scalar, b Scalar) Scalar {
	_ = "STUB: not implemented"
	return *new(Scalar)
}

func (s *wScl) Add(a, b Scalar) Scalar { _ = "STUB: not implemented"; return *new(Scalar) }

func (s *wScl) Sub(a, b Scalar) Scalar { _ = "STUB: not implemented"; return *new(Scalar) }

func (s *wScl) Mul(a, b Scalar) Scalar { _ = "STUB: not implemented"; return *new(Scalar) }

func (s *wScl) Neg(a Scalar) Scalar { _ = "STUB: not implemented"; return *new(Scalar) }

func (s *wScl) Inv(a Scalar) Scalar { _ = "STUB: not implemented"; return *new(Scalar) }

func (s *wScl) MarshalBinary() (data []byte, err error) { _ = "STUB: not implemented"; return nil, nil }

func (s *wScl) UnmarshalBinary(b []byte) error { _ = "STUB: not implemented"; return nil }

func (s *wScl) Marshal(b *cryptobyte.Builder) error { _ = "STUB: not implemented"; return nil }

func (s *wScl) Unmarshal(str *cryptobyte.String) bool { _ = "STUB: not implemented"; return false }

// isLessThan returns 1 if 0 <= x < y, otherwise 0. Assumes that slices have the same length.
func isLessThanBE(x, y []byte) int { _ = "STUB: not implemented"; return 0 }

func (g wG) mapToCurveParams() (mapping func(u *big.Int) *wElt, h crypto.Hash, L uint) {
	_ = "STUB: not implemented"
	return nil, *new(crypto.Hash), 0
}

func (g wG) sswu3mod4Map(u *big.Int, Z, C2 *big.Int) *wElt { _ = "STUB: not implemented"; return nil }

// 1.  c1 = (q - 3) / 4

// 1.  tv1 = u^2
// 2.  tv3 = Z * tv1
// 3.  tv2 = tv3^2
// 4.   xd = tv2 + tv3
// 5.  x1n = xd + 1
// 6.  x1n = x1n * B
//
// 7.   xd = -A * xd
// 8.   e1 = xd == 0
//
// 9.   xd = CMOV(xd, Z * A, e1)
// 10. tv2 = xd^2
// 11. gxd = tv2 * xd
// 12. tv2 = A * tv2
// 13. gx1 = x1n^2
// 14. gx1 = gx1 + tv2
// 15. gx1 = gx1 * x1n
// 16. tv2 = B * gxd
// 17. gx1 = gx1 + tv2
// 18. tv4 = gxd^2
// 19. tv2 = gx1 * gxd
// 20. tv4 = tv4 * tv2
// 21.  y1 = tv4^c1
// 22.  y1 = y1 * tv2
// 23. x2n = tv3 * x1n
// 24.  y2 = y1 * c2
// 25.  y2 = y2 * tv1
// 26.  y2 = y2 * u
// 27. tv2 = y1^2
// 28. tv2 = tv2 * gxd
// 29.  e2 = tv2 == gx1
// 30.  xn = CMOV(x2n, x1n, e2)
// 31.   y = CMOV(y2, y1, e2)
// 32.  e3 = sgn0(u) == sgn0(y)
//
// 33.   y = CMOV(-y, y, e3)
//
// 34. return (xn, xd, y, 1)

var (
	// Order of the P256 group.
	orderP256 = [...]byte{
		0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00,
		0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
		0xbc, 0xe6, 0xfa, 0xad, 0xa7, 0x17, 0x9e, 0x84,
		0xf3, 0xb9, 0xca, 0xc2, 0xfc, 0x63, 0x25, 0x51,
	}
	// Order of the P384 group.
	orderP384 = [...]byte{
		0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
		0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
		0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
		0xc7, 0x63, 0x4d, 0x81, 0xf4, 0x37, 0x2d, 0xdf,
		0x58, 0x1a, 0x0d, 0xb2, 0x48, 0xb0, 0xa7, 0x7a,
		0xec, 0xec, 0x19, 0x6a, 0xcc, 0xc5, 0x29, 0x73,
	}
	// Order of the P521 group.
	orderP521 = [...]byte{
		0x01, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
		0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
		0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
		0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff,
		0xff, 0xfa, 0x51, 0x86, 0x87, 0x83, 0xbf, 0x2f,
		0x96, 0x6b, 0x7f, 0xcc, 0x01, 0x48, 0xf7, 0x09,
		0xa5, 0xd0, 0x3b, 0xb5, 0xc9, 0xb8, 0x89, 0x9c,
		0x47, 0xae, 0xbb, 0x6f, 0xb7, 0x1e, 0x91, 0x38,
		0x64, 0x09,
	}
)
